### ISSUE TITLE
Support for running static content apps on Apache HTTP Server

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/staticfile#39]
One thing to think supporting in this buildpack is the ability for users to use Apache HTTP Server to serve static content apps. 

Provided the app has a buildpack.yml with the structure below, users would run `pack build --buildpack paketo-buildpacks/httpd --buildpack paketo-buildpacks/staticfile`.
Buildpack.yml
```
staticfile:
  httpd:
    root: "public"
     ...... # other keys
```
